source 'https://www.rubygems.org'

gem 'appium_console', require: false
gem 'appium_lib'
gem 'cucumber'
gem 'httpclient'
gem 'rspec-expectations'
gem 'rubocop', '~> 0.49.1', require: false
gem 'nokogiri', '~> 1.10', '>= 1.10.3'
gem 'ffi'
gem 'httparty'
gem 'faker'
gem 'rspec'
gem 'json'